// <auto-generated />
using E_Conc.Data;
using E_Conc.Enum;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace E_Conc.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20180426015338_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("E_Conc.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Sigla");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("E_Conc.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ProdutoId");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("E_Conc.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Arquivo")
                        .IsRequired();

                    b.Property<int>("Categoria");

                    b.Property<int?>("CursoId");

                    b.Property<bool>("Disponivel");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("E_Conc.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CursoId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("Instituicao")
                        .IsRequired();

                    b.Property<string>("InstituicaoSigla");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("Ra")
                        .HasMaxLength(25);

                    b.Property<string>("Senha")
                        .IsRequired();

                    b.Property<string>("Telefone")
                        .HasMaxLength(35);

                    b.Property<int>("TipoUsuario");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("E_Conc.Models.ItemPedido", b =>
                {
                    b.HasOne("E_Conc.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.HasOne("E_Conc.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("E_Conc.Models.Produto", b =>
                {
                    b.HasOne("E_Conc.Models.Curso")
                        .WithMany("Produtos")
                        .HasForeignKey("CursoId");

                    b.HasOne("E_Conc.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("E_Conc.Models.Usuario", b =>
                {
                    b.HasOne("E_Conc.Models.Curso")
                        .WithMany("Usuarios")
                        .HasForeignKey("CursoId");
                });
#pragma warning restore 612, 618
        }
    }
}
