// <auto-generated />
using E_Conc.Data;
using E_Conc.Enum;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace E_Conc.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("E_Conc.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CursoId");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Instituicao")
                        .IsRequired();

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int>("Ra");

                    b.Property<string>("Senha")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("E_Conc.Models.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Sigla");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("E_Conc.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Disponivel");

                    b.Property<int?>("ProdutoId");

                    b.Property<int?>("SolicitanteId");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("E_Conc.Models.Orientador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Instituicao")
                        .IsRequired();

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Senha")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Orientadores");
                });

            modelBuilder.Entity("E_Conc.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Arquivo")
                        .IsRequired();

                    b.Property<int>("Categoria");

                    b.Property<int?>("CursoId");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int?>("OrientadorId");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("OrientadorId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("E_Conc.Models.Aluno", b =>
                {
                    b.HasOne("E_Conc.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId");
                });

            modelBuilder.Entity("E_Conc.Models.ItemPedido", b =>
                {
                    b.HasOne("E_Conc.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");

                    b.HasOne("E_Conc.Models.Aluno", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId");
                });

            modelBuilder.Entity("E_Conc.Models.Produto", b =>
                {
                    b.HasOne("E_Conc.Models.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId");

                    b.HasOne("E_Conc.Models.Orientador", "Orientador")
                        .WithMany("Produtos")
                        .HasForeignKey("OrientadorId");
                });
#pragma warning restore 612, 618
        }
    }
}
